include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

variables:
  DEPLOY_ENVIRONMENT_URL: https://${CI_PROJECT_NAME}.${DD_TRAEFIK_DOMAIN}

.deploy:
  environment:
    url: ${DEPLOY_ENVIRONMENT_URL}
