version: '3.7'

services:
  traefik:
    image: traefik:${IMAGE_TAG:-latest}
    command:
      - "--api"
      - "--logLevel=${TRAEFIK_LOG_LEVEL}"
      - "--sendAnonymousUsage=true"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--maxIdleConnsPerHost=${TRAEFIK_MAX_IDLE_CONNECTIONS}"
      - "--forwardingtimeouts.dialtimeout=${TRAEFIK_DIAL_TIMEOUT}"
      - "--forwardingtimeouts.responseheadertimeout=0s"
      - "--respondingtimeouts.idletimeout=${TRAEFIK_IDLE_TIMEOUT}"
      - "--respondingtimeouts.readtimeout=0s"
      - "--respondingtimeouts.writetimeout=0s"
      - "--docker"
      - "--docker.watch"
      - "--docker.network=${TRAEFIK_NET_NAME}"
      - "--docker.domain=${PUBLIC_HOSTNAME}"
      - "--docker.swarmmode"
      - "--acme"
      - "--acme.onhostrule"
      - "--acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entrypoint=https"
      - "--acme.httpchallenge.entrypoint=http"
      - "--acme.keytype=${TRAEFIK_ACME_KEY_TYPE}"
    networks:
      - traefik-net
    ports:
      - target: 80
        published: 80
        mode: ${TRAEFIK_PORT_MODE}
      - target: 443
        published: 443
        mode: ${TRAEFIK_PORT_MODE}
    volumes:
      - acme-vol:/etc/traefik/acme
      - tmp-vol:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: ${TRAEFIK_REPLICAS}
      labels:
        traefik.frontend.auth.basic.users: ${TRAEFIK_UI_AUTH}
        traefik.frontend.rule: Host:${TRAEFIK_SUBDOMAIN}.${PUBLIC_HOSTNAME}
        traefik.backend: traefik
        traefik.port: '8080'
      restart_policy:
        delay: ${TRAEFIK_RESTART_POLICY_DELAY}
        window: ${TRAEFIK_RESTART_POLICY_WINDOW}
      resources:
        limits:
          cpus: "${TRAEFIK_LIMITS_CPUS}"
          memory: ${TRAEFIK_LIMITS_MEMORY}
        reservations:
          memory: ${TRAEFIK_RESERVATIONS_MEMORY}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME}
    driver: overlay
    attachable: ${TRAEFIK_NET_ATTACHABLE:-true}

volumes:
  acme-vol:
    name: ${TRAEFIK_ACME_VOL_NAME:-traefik-acme-vol}

  tmp-vol:
    name: ${TRAEFIK_TMP_VOL_NAME:-traefik-tmp-vol}
