version: '3.7'
services:
  traefik:
    image: traefik:${IMAGE_TAG:-latest}
    command:
      - "--api"
      - "--logLevel=INFO"
      - "--forwardingtimeouts.dialtimeout=15s"
      - "--forwardingtimeouts.responseheadertimeout=15s"
      - "--respondingtimeouts.idletimeout=30s"
      - "--respondingtimeouts.readtimeout=1m"
      - "--respondingtimeouts.writetimeout=1m"
      - "--docker"
      - "--docker.domain=${PUBLIC_HOSTNAME}"
      - "--docker.watch"
      - "--docker.swarmmode"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.onhostrule"
      - "--acme.email=${ACME_EMAIL}"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entrypoint=https"
      - "--acme.httpchallenge.entrypoint=http"
      - "--acme.keytype=RSA4096"
    networks:
      - traefik-net
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
    volumes:
      - traefik-acme-vol:/etc/traefik/acme
      - traefik-tmp-vol:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.docker.network: traefik-net
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:traefik.${PUBLIC_HOSTNAME}
        traefik.port: "8080"
        traefik.backend: traefik
      restart_policy:
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '2'
          memory: 128M
        reservations:
          memory: 103M

networks:
  traefik-net:
    name: traefik-net
    driver: overlay
    attachable: true

volumes:
  traefik-acme-vol:
    name: traefik-acme-vol

  traefik-tmp-vol:
    name: traefik-tmp-vol
