version: '3.7'

services:
  traefik:
    image: ${IMAGE_NAME:-traefik}:${IMAGE_TAG:-latest}
    environment:
      TRAEFIK_API:
      TRAEFIK_API_DASHBOARD:
      TRAEFIK_API_INSECURE:
      TRAEFIK_PING:
      TRAEFIK_PING_ENTRYPOINT:
      TRAEFIK_LOG_LEVEL:
      TRAEFIK_ACCESSLOG_FILEPATH:
      TRAEFIK_ACCESSLOG_FILTERS_STATUSCODES:
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE:
      TRAEFIK_GLOBAL_CHECKNEWVERSION:
      TRAEFIK_SERVERSTRANSPORT_MAXIDLECONNSPERHOST:
      TRAEFIK_SERVERSTRANSPORT_FORWARDINGTIMEOUTS_DIALTIMEOUT:
      TRAEFIK_SERVERSTRANSPORT_FORWARDINGTIMEOUTS_IDLECONNTIMEOUT:
      TRAEFIK_SERVERSTRANSPORT_FORWARDINGTIMEOUTS_RESPONSEHEADERTIMEOUT:
      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: :${HTTP_INTERNAL_PORT}
      TRAEFIK_ENTRYPOINTS_HTTP_TRANSPORT_RESPONDINGTIMEOUTS_IDLETIMEOUT:
      TRAEFIK_ENTRYPOINTS_HTTP_TRANSPORT_RESPONDINGTIMEOUTS_READTIMEOUT:
      TRAEFIK_ENTRYPOINTS_HTTP_TRANSPORT_RESPONDINGTIMEOUTS_WRITETIMEOUT:
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: :${HTTPS_INTERNAL_PORT}
      TRAEFIK_ENTRYPOINTS_HTTPS_TRANSPORT_RESPONDINGTIMEOUTS_IDLETIMEOUT:
      TRAEFIK_ENTRYPOINTS_HTTPS_TRANSPORT_RESPONDINGTIMEOUTS_READTIMEOUT:
      TRAEFIK_ENTRYPOINTS_HTTPS_TRANSPORT_RESPONDINGTIMEOUTS_WRITETIMEOUT:
      TRAEFIK_PROVIDERS_DOCKER:
      TRAEFIK_PROVIDERS_DOCKER_WATCH:
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: ${TRAEFIK_NET_NAME}
      TRAEFIK_PROVIDERS_DOCKER_SWARMMODE:
      TRAEFIK_PROVIDERS_DOCKER_SWARMMODEREFRESHSECONDS:
      TRAEFIK_CERTIFICATESRESOLVERS_DEFAULT_ACME_EMAIL: ${TRAEFIK_ACME_EMAIL}
      TRAEFIK_CERTIFICATESRESOLVERS_DEFAULT_ACME_STORAGE:
      TRAEFIK_CERTIFICATESRESOLVERS_DEFAULT_ACME_HTTPCHALLENGE:
      TRAEFIK_CERTIFICATESRESOLVERS_DEFAULT_ACME_HTTPCHALLENGE_ENTRYPOINT:
      TRAEFIK_CERTIFICATESRESOLVERS_DEFAULT_ACME_TLSCHALLENGE:
      TRAEFIK_CERTIFICATESRESOLVERS_DEFAULT_ACME_KEYTYPE:
      TRAEFIK_METRICS_PROMETHEUS:
      TRAEFIK_METRICS_PROMETHEUS_ADDENTRYPOINTSLABELS:
      TRAEFIK_METRICS_PROMETHEUS_ADDSERVICESLABELS:
      TRAEFIK_METRICS_PROMETHEUS_BUCKETS:
      TRAEFIK_METRICS_PROMETHEUS_ENTRYPOINT:
    networks:
      traefik-net:
    ports:
      - target: ${HTTP_INTERNAL_PORT}
        published: ${HTTP_PORT}
        protocol: tcp
        mode: ${PORT_MODE}
      - target: ${HTTP_INTERNAL_PORT}
        published: ${HTTP_PORT}
        protocol: udp
        mode: ${PORT_MODE}
      - target: ${HTTPS_INTERNAL_PORT}
        published: ${HTTPS_PORT}
        protocol: tcp
        mode: ${PORT_MODE}
      - target: ${HTTPS_INTERNAL_PORT}
        published: ${HTTPS_PORT}
        protocol: udp
        mode: ${PORT_MODE}
    volumes:
      - acme-vol:/acme
      - tmp-vol:/tmp
      - log-vol:/log
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: traefik healthcheck
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-30s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-0s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      placement:
        constraints:
          - ${PLACEMENT_CONSTRAINT:-node.hostname == node}
      labels:
        traefik.http.routers.traefik-redirect.entrypoints: http
        traefik.http.routers.traefik-redirect.rule: PathPrefix(`/`)
        traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme: https
        traefik.http.routers.traefik-redirect.middlewares: traefik-https-redirect
        traefik.http.services.traefik-redirect.loadbalancer.server.port: 0

        traefik.http.routers.traefik-dashboard.entrypoints: https
        traefik.http.routers.traefik-dashboard.tls.certresolver: default
        traefik.http.routers.traefik-dashboard.rule: Host(`${TRAEFIK_SUBDOMAIN:-traefik}.${TRAEFIK_DOMAIN}`)
        traefik.http.middlewares.traefik-dashboard-auth.basicauth.users: ${TRAEFIK_AUTH}
        traefik.http.routers.traefik-dashboard.middlewares: traefik-dashboard-auth
        traefik.http.routers.traefik-dashboard.service: api@internal
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-2}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-32M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    attachable: ${TRAEFIK_NET_ATTACHABLE:-true}

volumes:
  acme-vol:
    name: ${ACME_VOL_NAME:-traefik-acme-vol}

  tmp-vol:
    name: ${TMP_VOL_NAME:-traefik-tmp-vol}

  log-vol:
    name: ${LOG_VOL_NAME:-traefik-log-vol}
